<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Dr. Meinaier Vitamin C Sugar Scrub (510g)',
                'description' => 'Gentle exfoliating body and face sugar scrub enriched with vitamin C and natural orange extract. Gently removes dead skin cells, unclogs pores, and restores a vibrant natural glow. Exfoliant & body care.',
                'price' => 3200.00,
                'image_url' => '/storage/products/1gxOidf3DIsRMSCwAfAVOyPYlibB3783StaS8kuZ.webp',
                'is_active' => true,
            ],
            [
                'name' => 'The Ordinary Complete Skincare Routine Set',
                'description' => 'Premium skincare regimen bundle featuring Coverage Foundation, Azelaic Acid Suspension 10%, Hyaluronic Acid 2% + B5 hydration serum, and Natural Moisturizing Factors + HA cream. Multi-step cleanser, serum, and moisturizer care.',
                'price' => 8500.00,
                'image_url' => '/storage/products/1rGpxobLIlp558oLe8YNXbebJr4tEMUPDuQ3ODRN.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe SA Smoothing Cleanser (473ml)',
                'description' => 'Dermatologist-developed exfoliating gel cleanser formulated with salicylic acid, hyaluronic acid, and 3 essential ceramides. Gently exfoliates and softens rough, bumpy skin without disrupting the barrier. Cleanser & exfoliant.',
                'price' => 4800.00,
                'image_url' => '/storage/products/3ghE1y64EQC9sOSI4gqoe5S8ajapeInX5f7sXQ98.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Ailke Superior Whitening & Regenerating Cleanser (120g)',
                'description' => 'Brightening facial wash formulated with pearl extracts and natural botanicals to clarify complexion, reduce blemishes, and provide smooth youthful skin. Foaming cleanser for everyday radiance.',
                'price' => 2800.00,
                'image_url' => '/storage/products/5Q59hE4L8j5vfQkjesupxinYWbhvyoQdHb7mPvv5.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Medicube Kojic Acid Turmeric Toning Cleanser (120g)',
                'description' => 'Powerful toning gel cleanser with 100 Kojic Acid and turmeric root extract. Targets hyperpigmentation, dark spots, and dullness while providing gentle daily foaming exfoliant cleanse.',
                'price' => 4200.00,
                'image_url' => '/storage/products/6vtyhM4hN3UTrMuOctKJMlYvMU4hpkOa5z9fbme5.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Yimiaosi Whitening Sunscreen Cream SPF 50+ PA+++',
                'description' => 'Broad-spectrum UV protection cream with brightening niacinamide formula. Water-resistant, non-greasy shield against UVA/UVB rays that protects against sun damage and premature aging. Sunscreen.',
                'price' => 3000.00,
                'image_url' => '/storage/products/8GUC868FEDk6SnHoL4b8WYzRjBCnKM8cx6lsw2XN.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Skin Aqua Tone Up UV Essence SPF 50+ PA++++ (50ml)',
                'description' => 'Color-correcting lightweight sunscreen essence that neutralizes redness while delivering maximum SPF 50+ protection. Infused with hyaluronic acid and vitamin C for a fresh radiant finish. Sunscreen.',
                'price' => 3800.00,
                'image_url' => '/storage/products/9hhstJwsmBE4i0csOrykqQA9nbnFvFuIowayCKGW.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Cetaphil Moisturizing Cream with Prebiotic Aloe (453g)',
                'description' => 'Rich, non-greasy cream clinically proven to hydrate dry to very dry sensitive skin for 48 hours. Formulated with niacinamide, panthenol, and prebiotic aloe. Intense hydrating moisturizer.',
                'price' => 5200.00,
                'image_url' => '/storage/products/A1fQqoJvj6IjK6DMV8PmjLkUR0p3jvFCZjv516t1.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Nivea Soft Refreshingly Soft Moisturising Cream (300ml)',
                'description' => 'Fast-absorbing, light daily moisturizer enriched with Jojoba oil and Vitamin E. Delivers deep moisture to face, hands, and body, leaving skin remarkably soft and energized. Moisturizer.',
                'price' => 2900.00,
                'image_url' => '/storage/products/Crmjst9XLAk9n982EnRtvhiRpPueTJK5lCnsCxbX.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'The Ordinary Glycolic Acid 7% Toning Solution (240ml)',
                'description' => 'Exfoliating toner formulated with 7% glycolic acid, Tasmanian pepperberry, and aloe vera. Promotes skin radiance, improves clarity, and balances uneven texture. Gentle chemical exfoliant.',
                'price' => 4500.00,
                'image_url' => '/storage/products/DEEcyNcDSC33abn37hcfclgekcR7TZXuZlByJEkO.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Neutrogena Hydro Boost Water Gel Cleanser (200ml)',
                'description' => 'Lightweight gel cleanser activated with water to gently remove dirt, oil, and makeup while locking in essential hydration with hyaluronic acid. Fresh, revitalizing face cleanser.',
                'price' => 3900.00,
                'image_url' => '/storage/products/EoRdzo2gqEpIsY9huO2unjieYfsf3EdNKgtlZbhz.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Nicor Ice Point Protection Sunscreen Cream SPF 50+',
                'description' => 'Ultra-refreshing, cooling sunscreen cream providing broad-spectrum UVA and UVB defense. Sweat-resistant, non-sticky formula suitable for outdoor activities and daily sun protection.',
                'price' => 2800.00,
                'image_url' => '/storage/products/Etld6AkPBnEaNFmlO02NriylhydOaISTeEMELF8Y.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'The Ordinary Everyday Radiance & Moisture Skincare Routine',
                'description' => 'Complete clinical skincare set featuring Hyaluronic Acid 2% + B5 hydration serum, Natural Moisturizing Factors + HA cream, and specialized balancing treatments. Ideal daily moisturizer & serum combo.',
                'price' => 8200.00,
                'image_url' => '/storage/products/F8CgMiw5WmKf2z758qfSh13rUma0DiDAGu8jDSeC.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Cetaphil Gentle Skin Cleanser for Sensitive Skin (500ml)',
                'description' => 'Award-winning soap-free cleanser that defends against 5 signs of skin sensitivity. Hydrates while cleansing with hydrating glycerin, vitamin B5, and essential B3. Daily gentle cleanser.',
                'price' => 5400.00,
                'image_url' => '/storage/products/JR7VOd0zeEABzN6tKMy6BlW0Q1wXmz0Muad1IJlZ.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Kojie San Skin Lightening Kojic Acid Soap (Trio Pack 100g x 3)',
                'description' => 'Authentic Kojic Acid brightening soap bar with zero pigment light technology. Effectively fades dark spots, acne scars, and uneven pigmentation. Gentle exfoliating wash & cleanser.',
                'price' => 3200.00,
                'image_url' => '/storage/products/LmAWB6rB28FYB08EcWvzbzQ5go8sIz3PC8ERIWIJ.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Eucerin Sun Protection Pigment Control Sun Fluid SPF 50+ (50ml)',
                'description' => 'Advanced facial sunscreen featuring patented Thiamidol to visibly reduce dark spots and prevent their reappearance. High UVA/UVB spectral technology. Sunscreen for radiant, even tone.',
                'price' => 5800.00,
                'image_url' => '/storage/products/OkM2EACTsZN4eNQFROaJq3pFZi5bmReubWLnnDen.webp',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe AM Facial Moisturizing Lotion SPF 30 (89ml)',
                'description' => 'Daily morning moisturizer with broad-spectrum SPF 30 sunscreen. Features 3 essential ceramides, hydrating hyaluronic acid, and soothing niacinamide with MVE delivery technology. Daily moisturizer.',
                'price' => 4800.00,
                'image_url' => '/storage/products/Oon2TpZFqto9LNVUnTiFZwxvMefBVAYgLwfTIMtG.webp',
                'is_active' => true,
            ],
            [
                'name' => 'La Roche-Posay Effaclar Purifying Foaming Gel (400ml)',
                'description' => 'Dermatological foaming cleanser specially formulated for oily, blemish-prone, and sensitive skin. Eliminates excess sebum and impurities while preserving skin\'s physiological balance. Cleanser.',
                'price' => 6200.00,
                'image_url' => '/storage/products/QZyJDwK1FOfiS7slmzaQmvKVDTZ5P1yZt8uFGDPM.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Facetheory Wonder Cream Instant Glow Reviver (50ml)',
                'description' => 'Luxurious brightening moisturizer enriched with active botanical complex, shea butter, and vitamin C. Restores skin vitality and gives an instant youthful glow. Rich day and night moisturizer.',
                'price' => 4600.00,
                'image_url' => '/storage/products/R3ALPqmM0IN3ZgoHyMxpbATmYVrdzLkGjpct61P2.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'St. Ives Energizing Scrub Coconut & Coffee (170g)',
                'description' => 'Invigorating face scrub made with 100% natural walnut shell powder and coffee extract. Deeply cleanses and exfoliates dull skin, leaving you fresh and energized. Exfoliant & cleanser.',
                'price' => 2800.00,
                'image_url' => '/storage/products/RCcMbwu59avPNCSHnFyvbjC8QJ7DGHPJMGdFGXX0.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Renewing SA Cleanser (237ml)',
                'description' => 'Non-comedogenic, non-drying cleanser formulated with salicylic acid, vitamin D, and ceramides to exfoliate and detoxify without stripping natural oils. Gentle smoothing cleanser & exfoliant.',
                'price' => 4200.00,
                'image_url' => '/storage/products/RbOtHACoVWxFRQ2Qt8rZw63Llm1y0HgNTBwwJTH8.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Skin Aqua Sunplay Tone Up UV Essence Mint Green (50ml)',
                'description' => 'Mint green color-correcting sunscreen designed to calm redness and acne spots. Lightweight water-feel texture with SPF 50+ PA++++ broad spectrum sun defense. Sunscreen.',
                'price' => 3800.00,
                'image_url' => '/storage/products/S8yWAg5rTe1f2qv0yGP4rt0F5spXFhvDFmMBqB1J.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Neutrogena Hydro Boost Exfoliator Smoothing Gel (150ml)',
                'description' => 'Hydrating gel exfoliator with soft micro-beads that polish skin surface and melt away dullness. Loaded with hyaluronic acid to preserve moisture barrier. Daily gentle exfoliant & cleanser.',
                'price' => 3900.00,
                'image_url' => '/storage/products/Sd9UdwYRhtqIiJIVD1ynqW0AeAh7rB9wmn5lUm4y.webp',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe AM Facial Moisturizing Lotion with InVisibleZinc SPF 30',
                'description' => 'Hydrating day lotion powered by micronized zinc oxide sunscreen, hyaluronic acid, and ceramides. Calms, repairs barrier, and shields against UVA/UVB rays without white cast. Moisturizer & sunscreen.',
                'price' => 4900.00,
                'image_url' => '/storage/products/TPWFKMQwbRD8dQO6t5pVV3gdu5VMiomeTAVpwmuF.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Hydrating Facial Cleanser (237ml)',
                'description' => 'Lotion-like gentle facial wash formulated with ceramides and hyaluronic acid to cleanse without stripping moisture. Restores the skin barrier for normal to dry skin. Cleanser.',
                'price' => 4200.00,
                'image_url' => '/storage/products/TbbWeLfX2PRhj53m6qEUSjmEnRXtk4fPSEKreX3p.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Cetaphil Moisturising Cream Mega Jar (550g)',
                'description' => 'Dermatologically tested ultra-rich cream for very dry to sensitive skin. Provides long-lasting 48-hour moisture nourishment with sweet almond oil and essential vitamins. Mega size moisturizer.',
                'price' => 5900.00,
                'image_url' => '/storage/products/TwaUQtOHya9LA9HYfk45YSF3fIeXEAVeMWqtVqj3.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Sandalwood Luxury Beard Care Kit (Oil & Balm)',
                'description' => 'Complete men\'s grooming set including nourishing Sandalwood Beard Oil and styling conditioning Beard Balm. Softens coarse hair, reduces beard itch, and moisturizes skin underneath.',
                'price' => 3500.00,
                'image_url' => '/storage/products/TzhqE10jpg1seAJnAafwihlKl9umd6nLMtdhKaoW.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Moisturizing Cream with 3 Essential Ceramides (453g)',
                'description' => 'Barrier-restoring rich cream formulated with patented MVE delivery technology, 3 ceramides, and hyaluronic acid. Suitable for sensitive, eczema-prone skin on face and body. Moisturizer.',
                'price' => 5300.00,
                'image_url' => '/storage/products/UaIVBnxqSkI1kHb1wXhpufROxDQVtbczpB9zdnLE.webp',
                'is_active' => true,
            ],
            [
                'name' => 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF 50+ (50ml)',
                'description' => 'Breakthrough sunscreen with Mexoryl 400 filter protecting against ultra-long UVA rays. Ultra-resistant against water, sweat, and sand. Non-stinging, lightweight fluid sunscreen.',
                'price' => 6200.00,
                'image_url' => '/storage/products/WcyQuIt4ZNobQU3Pjk9Hb4OQO6YWQZSwBv02gmp0.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Good Molecules Overnight Exfoliating Treatment (30ml)',
                'description' => 'Potent blend of 10% AHA (glycolic & lactic acid) and BHA (salicylic acid) to resurface, unclog pores, and reveal glowing smooth skin overnight. Chemical exfoliant & serum.',
                'price' => 3900.00,
                'image_url' => '/storage/products/WshQ7b6zHNl48MyTYvSrjIfd6U25IFFYObx4gGsA.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Beauty of Joseon Relief Sun: Rice + Probiotics SPF 50+ (50ml)',
                'description' => 'Cult-favorite Korean organic sunscreen formulated with 30% rice extract and grain fermented probiotics. Provides deep nourishment and glow without greasy residue. Daily sunscreen.',
                'price' => 4400.00,
                'image_url' => '/storage/products/X8ooZHGH6NQHQnFTdxxPczZfAL4ghZIE5qi6QLWO.png',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Hydrating Mineral Sunscreen Face Sheer Tint SPF 50',
                'description' => '100% mineral sunscreen with titanium dioxide and zinc oxide. Tinted formula blends seamlessly into all skin tones while delivering all-day moisture and broad spectrum UV protection. Sunscreen.',
                'price' => 5100.00,
                'image_url' => '/storage/products/Zt3VbPXF3QXAYwiSXb4TKiOCYOeaKn16Iiu7q87i.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Aveeno Calm + Restore Nourishing Oat Cleanser (200ml)',
                'description' => 'Dermatologist-recommended milky gel cleanser formulated with prebiotic oat and calming feverfew. Gently washes away impurities while soothing irritated, sensitive skin. Cleanser.',
                'price' => 4200.00,
                'image_url' => '/storage/products/d6YaqcEkVzHEvvTpUHJSLB5ogAmwWzvRtVL0Wdhv.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Cosmo Beauty Treat Papaya Exfoliating Face Scrub (170ml)',
                'description' => 'Invigorating face scrub with natural papaya enzymes and exfoliating granules. Brightens complexions, fades dull patches, and promotes cellular renewal. Facial exfoliant.',
                'price' => 2600.00,
                'image_url' => '/storage/products/dSQZFHtrUYCERhWDa4j1Bn1tLd4XZE3xmhWqFZm6.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Bioré UV Aqua Rich Watery Essence SPF 50+ PA++++ (50g)',
                'description' => 'Micro defense formula watery essence sunscreen that spreads effortlessly and absorbs instantly without white cast. Infused with hyaluronic acid and royal jelly extract. Sunscreen.',
                'price' => 4100.00,
                'image_url' => '/storage/products/feHQRrmzOOWhLqx8OacvjaHRbKplj7hordLGrRCS.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Glow Botanicals Pure Botanical Face & Body Oil (30ml)',
                'description' => 'Cold-pressed luxury facial oil rich in antioxidants, squalane, and rosehip extract. Restores elasticity, seals in deep moisture, and leaves skin with a radiant dewy glow. Hydrating oil & moisturizer.',
                'price' => 3600.00,
                'image_url' => '/storage/products/fgFL8KR6tz0OSMgXF85JsuQmfifrfzjTUdkJKgWh.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Hydrating Facial Cleanser Value Pack (473ml / 16 oz)',
                'description' => 'Economical large pump bottle of CeraVe\'s iconic hydrating wash. Clinically proven to cleanse, hydrate, and maintain skin barrier with 3 essential ceramides. Gentle cleanser.',
                'price' => 5600.00,
                'image_url' => '/storage/products/hEpgLzQWZUfNHhCxYAo8t7HA1UOjtmzlVk01pVQh.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Curology Complete Custom Skincare Trio Box Set',
                'description' => 'Customized skincare set including gentle cleanser, targeted active serum treatment, and rich hydrating moisturizer. Designed to clear blemishes and rebalance sensitive skin. Cleanser, serum & moisturizer.',
                'price' => 7900.00,
                'image_url' => '/storage/products/hoQFFDEKuylahyQnSjfilo9X9cCIJjHxrMq2u8jw.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Disaar Collagen & Snail Sunscreen Cream SPF 50+ (50g)',
                'description' => 'Dual-action sun protection cream enriched with snail secretion filtrate and hydrolyzed collagen. Moisturizes, firms, and guards against premature photo-aging. Water-resistant sunscreen.',
                'price' => 2900.00,
                'image_url' => '/storage/products/jISSnTZ4Q7SUEOWJNW6iJbrqV7WGYApy0iZsMG5J.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Nivea Sun Triple Protect Extra Radiance Fluid SPF 50+ (40ml)',
                'description' => 'Ultra-lightweight daily sun fluid defending against UVA, UVB, and blue light. Formulated with Hokkaido rose extract for enhanced radiance and a smooth matte finish. Sunscreen.',
                'price' => 3700.00,
                'image_url' => '/storage/products/kRCTY2TazaQ1vi3hVu1eK2BUA4igwafNDN0DYjPE.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Valera Sun Block Gel UVA & UVB SPF 60 / SPF 90 (120ml)',
                'description' => 'High-potency sunblock gel offering maximum UVA and UVB protection. Oil-free, lightweight gel formula suitable for sensitive, acne-prone skin under intense sunlight. Sunscreen.',
                'price' => 3400.00,
                'image_url' => '/storage/products/m76VHPRUnKjv7S7t9drBWBpRa1qioXo7CaVfihlC.webp',
                'is_active' => true,
            ],
            [
                'name' => 'La Roche-Posay Toleriane Double Repair Face Moisturizer (75ml)',
                'description' => 'Dermatologist-formulated oil-free daily moisturizer with prebiotic thermal water, ceramide-3, and niacinamide. Provides 48-hour soothing hydration and restores skin barrier. Moisturizer.',
                'price' => 5900.00,
                'image_url' => '/storage/products/mSWzTlZy34hBS5AgkALOtWfIZhv96GxhW4ffJjeQ.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'CeraVe Hydrating Facial Cleanser Medium Size (355ml / 12 oz)',
                'description' => 'Daily moisturizing facial cleanser with essential ceramides and hyaluronic acid. Leaves skin feeling clean and refreshed without tight dryness. Fragrance-free cleanser.',
                'price' => 4700.00,
                'image_url' => '/storage/products/ojJsLPaGZgB8EOsBVfuRsxsXl0UGA74gqHoc3Wv0.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Clean & Clear Deep Action Exfoliating Cleanser (100g)',
                'description' => 'Oil-free cooling cream cleanser with gentle exfoliating micro-scrubbers. Cleanses deep down to the pores to lift dirt, excess oil, and impurities without over-drying. Cleanser & exfoliant.',
                'price' => 2700.00,
                'image_url' => '/storage/products/qSxZc25wu5cG1cNfm7pjP2Kyak3CdPynsRwfNPpv.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'La Roche-Posay Anthelios UVMune 400 Tinted Fluid SPF 50+',
                'description' => 'High-protection tinted sun fluid with Mexoryl 400 UV filter. Unifies skin tone, conceals minor blemishes, and offers invisible non-greasy broad spectrum sun defense. Tinted sunscreen.',
                'price' => 6400.00,
                'image_url' => '/storage/products/qrXj91trU2Kxu7GVgkcUQmNZuzN2zyLZyz3yuRCU.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Cetaphil Moisturising Lotion for Sensitive Skin (500ml)',
                'description' => 'Lightweight, fast-absorbing daily lotion with avocado oil, vitamins E, B3, and provitamin B5. Clinically proven to soothe skin and protect moisture barrier for 48 hours. Moisturizer.',
                'price' => 5100.00,
                'image_url' => '/storage/products/rb6xRnouUuNFQuJrm7vT1YQDzjOPs9QWJT9gAPQa.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Fixderma Shadow Sunscreen Cream SPF 50+ PA+++ (75g)',
                'description' => 'Dermatologist-recommended broad-spectrum sunscreen cream with micronized zinc oxide and titanium dioxide. Non-comedogenic, water-resistant formula suitable for all skin types. Sunscreen.',
                'price' => 3600.00,
                'image_url' => '/storage/products/uMqaQlOhA7hepSu1i86gyJsl6OA9Cw0awaPxvClU.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Rashel Sun Cream Hydrate SPF 50 PA+++ (60g)',
                'description' => '24-hour hydration soothing sun protection cream. Protects against UVA/UVB rays while infusing skin with moisture and calming botanical nutrients. Daily sunscreen.',
                'price' => 3100.00,
                'image_url' => '/storage/products/vO9tP2xNJxPmop7OmnWmyZ098c5wmFKCVcVODxtA.webp',
                'is_active' => true,
            ],
            [
                'name' => 'Anua Heartleaf Silky Moisture Sun Cream SPF 50+ PA++++',
                'description' => 'Calming Korean sun cream containing Heartleaf extract and panthenol. Leaves a silky, non-sticky matte finish while soothing redness and irritation. Sunscreen.',
                'price' => 4600.00,
                'image_url' => '/storage/products/wvnZuZWZaY8MtB1uLNSkqovzdcUFJLPsdECjmY45.webp',
                'is_active' => true,
            ],
            [
                'name' => 'The Ordinary Glycolic Acid 7% Exfoliating Toner Travel Size (100ml)',
                'description' => 'Convenient travel-sized exfoliating toner with 7% glycolic acid to gently dissolve surface dead cells, refine texture, and boost youthful radiance. Gentle exfoliant.',
                'price' => 3200.00,
                'image_url' => '/storage/products/x8mtQBolQFI9D2LIf4qzbVFYp1a5lZYNqwSjEluI.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Simple Kind to Skin Vital Vitamin Night Cream (50ml)',
                'description' => 'Nourishing night moisturizer packed with multi-vitamins (Pro-Vitamin B5, Vitamin E, Vitamin F, Glycerin). Restores and replenishes skin moisture while you sleep. Gentle night moisturizer.',
                'price' => 3300.00,
                'image_url' => '/storage/products/xU6lz0TtPrSW58CtHXsPX3mLMq8sRyiEiOvPaa2R.jpg',
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Rashel Anti-Aging Moisture Sun Cream SPF 60++ (60g)',
                'description' => 'Anti-aging facial sun protection cream with whitening complex and antioxidants. Guards against UV photoaging, dark spots, and moisture loss. Sunscreen.',
                'price' => 3300.00,
                'image_url' => '/storage/products/y9L3UdYLLwuvxjZWlerQDeREyNZTgpAchzSyGV6o.webp',
                'is_active' => true,
            ],
        ];

        foreach ($products as $item) {
            Product::firstOrCreate(
                ['image_url' => $item['image_url']],
                $item
            );
        }
    }
}
